# Generated by Django 3.2.7 on 2021-11-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('user_username', models.CharField(max_length=30)),
                ('teamid', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_name', models.CharField(max_length=50)),
                ('stat1', models.CharField(max_length=50)),
                ('stat2', models.CharField(max_length=50)),
                ('stat3', models.CharField(max_length=50)),
                ('stat4', models.CharField(max_length=50)),
                ('stat5', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
