# Generated by Django 3.2.7 on 2021-11-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_bracket_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='strings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.user'),
        ),
    ]
