# Generated by Django 3.2.7 on 2021-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211111_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket',
            old_name='strings',
            new_name='bracket',
        ),
    ]
