# Generated by Django 3.2.7 on 2021-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_strings_bracket_bracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user_username',
        ),
        migrations.AlterField(
            model_name='team',
            name='teamid',
            field=models.CharField(max_length=8),
        ),
    ]
