# Generated by Django 3.2.7 on 2021-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_user_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamid',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='team_name',
        ),
    ]
