# Generated by Django 3.2.7 on 2021-11-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20211114_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='num_members',
            field=models.IntegerField(default=2),
        ),
    ]
