# Generated by Django 3.2.7 on 2021-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_team_num_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='num_members',
            field=models.CharField(max_length=2),
        ),
    ]
