# Generated by Django 3.2.7 on 2021-11-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20211117_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserListModel',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='stat2',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='stat3',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='stat4',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='stat5',
        ),
    ]
