# Generated by Django 3.2.7 on 2021-11-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20211122_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='stat1',
        ),
        migrations.AddField(
            model_name='bracket',
            name='stats',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
