# Generated by Django 3.2.9 on 2021-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20211123_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favbracket',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
