# Generated by Django 3.2.9 on 2021-11-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_user_favbracket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favbracket',
        ),
    ]
