# Generated by Django 3.2.9 on 2021-11-24 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_user_favbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favbracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.bracket'),
        ),
    ]
