# Generated by Django 3.2.9 on 2021-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_user_favbracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favbracket',
            field=models.CharField(max_length=30),
        ),
    ]
