# Generated by Django 3.2.7 on 2021-11-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20211122_2342'),
        ('project', '0017_alter_bracket_user'),
    ]

    operations = [
    ]
