# Generated by Django 3.2.9 on 2021-11-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_bracket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='num_members',
            field=models.IntegerField(),
        ),
    ]
