# Generated by Django 3.2.9 on 2021-11-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_team_num_members'),
        ('project', '0018_merge_0012_auto_20211122_2342_0017_alter_bracket_user'),
    ]

    operations = [
    ]
