# Generated by Django 3.2.9 on 2021-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
    ]
