# Generated by Django 3.2.9 on 2021-11-28 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_posts_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='message',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500, unique=True),
        ),
    ]
