# Generated by Django 3.2.7 on 2021-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_posts_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket',
            old_name='bracket',
            new_name='bracket_16',
        ),
        migrations.AddField(
            model_name='bracket',
            name='bracket_2',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='bracket_32',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='bracket_4',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='bracket_64',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='bracket_8',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='winner',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
