# Generated by Django 3.2.7 on 2021-12-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20211129_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favbracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.bracket'),
        ),
    ]
