# Generated by Django 3.2.7 on 2021-12-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_user_favbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
